[build]
bin = "bin/main" # output binary location
cmd = "go build -o ./bin/main" # build command
include_ext = ["go", "tpl", "tmpl", "html"] # file extensions to watch
exclude_dir = ["vendor", "bin"] # directories to exclude from watching